use jdk21
it-at-m/refarch pull request #16
Opened 2024-07-18 12:44 UTC by simonhir

**Description**

Use jdk 21 instead of 17

2024-07-22 12:23 UTC, devtobi requested changes
Small pom change needed, I guess you checked the rest of the dependencies (especially Spring Boot) for JDK 21 compatibility, right?

2024-07-22 12:23 UTC, devtobi commented on refarch-gateway/pom.xml
> +        <maven.compiler.target>21</maven.compiler.target>
To keep this in sync with the other Java based projects I suggest using `java.version` as a variable and additionally set `maven.compiler.release`

```suggestion
        <maven.compiler.source>${java.version}</maven.compiler.source>
        <maven.compiler.target>${java.version}</maven.compiler.target>
        <maven.compiler.release>${java.version}</maven.compiler.release>
```

2024-07-23 05:14 UTC, simonhir commented
> I guess you checked the rest of the dependencies (especially Spring Boot) for JDK 21 compatibility, right?

Didn't check every single dependency but for functionality and Spring-Boot and Spring-Cloud support each at least jdk 21.

2024-07-23 08:29 UTC, devtobi approved these changes
LGTM

2024-07-26 04:50 UTC, merged